spring:
  application:
  datasource:
    username: root
    password: 169251
    url: jdbc:mysql://localhost:3306/ai_quizzer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: aiquizzer6@gmail.com
    password: xvmvckysamolkncb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

# AiQuizzer@2024

